- hosts: "{{ target_hosts | default('all') }}"  # Default to all hosts if target_hosts is not set
  gather_facts: no  # Disable fact gathering for performance

  tasks:
    - name: Parse dynamic playbooks
      set_fact:
        dynamic_playbooks: "{{ value | from_yaml }}"  
        # Convert the API-passed 'value' (string in YAML format) into a structured list

    - name: Validate parsed dynamic playbooks
      debug:
        msg: "{{ dynamic_playbooks }}"
      when: dynamic_playbooks is defined
      # Debugging: Show parsed playbooks in logs for validation

    - name: Run parsed tasks dynamically
      ansible.builtin.include_tasks:
        apply:
          tasks: "{{ dynamic_playbooks }}"
      when: dynamic_playbooks is defined and dynamic_playbooks | length > 0
      # Instead of including a separate file, apply tasks dynamically
