---
- name: Dynamic Playbook Template
  hosts: all
  gather_facts: false

  tasks:
    - name: "Process each item sequentially"
      include_tasks: dynamic_item_task.yml
      loop: "{{ tasksList }}"
      loop_control:
        label: "{{ item.name }}"
