---
- name: Dynamic Playbook Template
  hosts: all
  gather_facts: false

  tasks:
    - name: "Execute Command"
      become: yes
      command: "{{ item.command }}"
      when: item.command is defined
      loop: "{{ value }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "Execute Shell"
      become: yes
      shell: "{{ item.shell }}"
      when: item.shell is defined
      loop: "{{ value }}"
      loop_control:
        label: "{{ item.name }}"

    - name: "Show Debug Message"
      debug:
        msg: "{{ item.debug.msg }}"
      when: item.debug is defined
      loop: "{{ value }}"
      loop_control:
        label: "{{ item.name }}"
