---
- name: Hello World Sample
  hosts: all
  gather_facts: false

  tasks:
    - name: "Dynamic Tasks"
      debug:
        msg: "{{ item.debug.msg }}"
      loop: "{{ value }}"
      loop_control:
        label: "{{ item.name }}"
