---
- name: Dynamic Playbook Template
  hosts: all
  gather_facts: false

  tasks:
    - name: "Run Commands or Debug"
      include_tasks: 
        file: inline_task.yaml
        apply:
          loop: "{{ value }}"
          loop_control:
            loop_var: task_data

- name: inline_task.yaml
  tasks:
    - name: "Execute Command"
      command: "{{ task_data.command }}"
      when: task_data.command is defined

    - name: "Show Debug Message"
      debug:
        msg: "{{ task_data.debug.msg }}"
      when: task_data.debug is defined
